import type { AdminStats, DashboardStats, InventoryTransaction, PaginatedProducts, Product, Tenant, User } from './types'

const now = new Date()
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString()

export const demoUsers: User[] = [
  {
    id: 'demo-user-1',
    name: 'Aarav Mehta',
    email: 'aarav@northstar-retail.com',
    role: 'super_admin',
    tenant_id: null,
    is_active: true,
    created_at: daysAgo(120),
  },
  {
    id: 'demo-user-2',
    name: 'Nisha Rao',
    email: 'nisha@urbanbasket.com',
    role: 'retailer_admin',
    tenant_id: 'demo-tenant-1',
    is_active: true,
    created_at: daysAgo(86),
  },
  {
    id: 'demo-user-3',
    name: 'Kabir Sethi',
    email: 'kabir@urbanbasket.com',
    role: 'inventory_manager',
    tenant_id: 'demo-tenant-1',
    is_active: true,
    created_at: daysAgo(54),
  },
  {
    id: 'demo-user-4',
    name: 'Maya Kapoor',
    email: 'maya@freshcart.co',
    role: 'inventory_manager',
    tenant_id: 'demo-tenant-2',
    is_active: false,
    created_at: daysAgo(42),
  },
]

export const demoTenants: Tenant[] = [
  {
    id: 'demo-tenant-1',
    company_name: 'Urban Basket',
    contact_email: 'ops@urbanbasket.com',
    status: 'active',
    created_at: daysAgo(210),
  },
  {
    id: 'demo-tenant-2',
    company_name: 'FreshCart Supply',
    contact_email: 'hello@freshcart.co',
    status: 'active',
    created_at: daysAgo(175),
  },
  {
    id: 'demo-tenant-3',
    company_name: 'Metro Home Goods',
    contact_email: 'admin@metrohome.in',
    status: 'suspended',
    created_at: daysAgo(98),
  },
]

export const demoProducts: Product[] = [
  {
    id: 'demo-product-1',
    tenant_id: 'demo-tenant-1',
    product_name: 'Organic Basmati Rice 5kg',
    sku: 'UB-GRC-501',
    category: 'Grocery',
    brand: 'Harvest Lane',
    quantity: 128,
    price: 18.5,
    supplier: 'Greenfield Foods',
    warehouse_location: 'Aisle A-04',
    description: 'Premium aged basmati rice packed for high-turnover grocery shelves.',
    created_at: daysAgo(90),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-product-2',
    tenant_id: 'demo-tenant-1',
    product_name: 'Cold Brew Coffee Case',
    sku: 'UB-BEV-218',
    category: 'Beverages',
    brand: 'Black River',
    quantity: 8,
    price: 42,
    supplier: 'Brewline Distributors',
    warehouse_location: 'Cold Rack C-02',
    description: 'Pack of 24 ready-to-drink cold brew bottles.',
    created_at: daysAgo(76),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-product-3',
    tenant_id: 'demo-tenant-1',
    product_name: 'Cotton Bath Towel Set',
    sku: 'MHG-HME-884',
    category: 'Home',
    brand: 'Casa Loom',
    quantity: 46,
    price: 24.75,
    supplier: 'Metro Textiles',
    warehouse_location: 'Bay D-11',
    description: 'Soft 4-piece towel set in neutral retail colors.',
    created_at: daysAgo(64),
    updated_at: daysAgo(4),
  },
  {
    id: 'demo-product-4',
    tenant_id: 'demo-tenant-2',
    product_name: 'Bluetooth Barcode Scanner',
    sku: 'FC-EQP-034',
    category: 'Equipment',
    brand: 'ScanPro',
    quantity: 0,
    price: 89.99,
    supplier: 'Warehouse Tech Co.',
    warehouse_location: 'Secure Shelf S-03',
    description: 'Handheld scanner for checkout and stock counting teams.',
    created_at: daysAgo(48),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-product-5',
    tenant_id: 'demo-tenant-2',
    product_name: 'Reusable Produce Bags',
    sku: 'FC-ECO-119',
    category: 'Packaging',
    brand: 'EcoLoop',
    quantity: 310,
    price: 6.2,
    supplier: 'EcoLoop Packaging',
    warehouse_location: 'Aisle B-07',
    description: 'Mesh produce bags for sustainable grocery operations.',
    created_at: daysAgo(32),
    updated_at: daysAgo(5),
  },
]

export const demoTransactions: InventoryTransaction[] = [
  {
    id: 'demo-txn-1',
    tenant_id: 'demo-tenant-1',
    product_id: 'demo-product-1',
    transaction_type: 'stock_in',
    quantity: 72,
    notes: 'Weekly supplier delivery',
    timestamp: daysAgo(1),
    product: demoProducts[0],
    updated_by_user: demoUsers[2],
  },
  {
    id: 'demo-txn-2',
    tenant_id: 'demo-tenant-1',
    product_id: 'demo-product-2',
    transaction_type: 'stock_out',
    quantity: 24,
    notes: 'Storefront replenishment',
    timestamp: daysAgo(2),
    product: demoProducts[1],
    updated_by_user: demoUsers[1],
  },
  {
    id: 'demo-txn-3',
    tenant_id: 'demo-tenant-2',
    product_id: 'demo-product-4',
    transaction_type: 'stock_out',
    quantity: 5,
    notes: 'Assigned to new counters',
    timestamp: daysAgo(3),
    product: demoProducts[3],
    updated_by_user: demoUsers[3],
  },
  {
    id: 'demo-txn-4',
    tenant_id: 'demo-tenant-2',
    product_id: 'demo-product-5',
    transaction_type: 'adjustment',
    quantity: 12,
    notes: 'Cycle count correction',
    timestamp: daysAgo(5),
    product: demoProducts[4],
    updated_by_user: demoUsers[2],
  },
]

export const demoPaginatedProducts: PaginatedProducts = {
  items: demoProducts,
  total: demoProducts.length,
  page: 1,
  page_size: 15,
  total_pages: 1,
}

export const demoDashboardStats: DashboardStats = {
  total_products: demoProducts.length,
  low_stock_count: demoProducts.filter((product) => product.quantity <= 10).length,
  total_transactions: demoTransactions.length,
  total_value: demoProducts.reduce((sum, product) => sum + product.quantity * product.price, 0),
  recent_transactions: demoTransactions,
}

export const demoAdminStats: AdminStats = {
  total_tenants: demoTenants.length,
  total_products: demoProducts.length,
  active_users: demoUsers.filter((user) => user.is_active).length,
  total_transactions: demoTransactions.length,
  total_tenant_admins: demoUsers.filter((user) => user.role === 'retailer_admin').length,
  total_inventory_managers: demoUsers.filter((user) => user.role === 'inventory_manager').length,
  total_low_stock_alerts: demoProducts.filter((product) => product.quantity <= 10).length,
  active_tenants: demoTenants.filter((tenant) => tenant.status === 'active').length,
  inactive_tenants: demoTenants.filter((tenant) => tenant.status !== 'active').length,
}
